title: Willian Soncini
description: Senior Data Engineer | AWS | Python | Analytics Automation
url: "https://williansoncini.github.io"
baseurl: "/resume"
lang: en
theme: minima
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
sass:
  style: compressed